language: python

python:
    - "2.7"

sudo: required
dist: trusty

addons:
    apt:
        packages:
            - parallel

install:
    # Faup
    - git clone https://github.com/stricaud/faup.git
    - pushd faup/build
    - cmake .. && make
    - sudo make install
    - sudo ldconfig
    - popd
    - pushd faup/src/lib/bindings/python
    - python setup.py install
    - popd
    # redis
    - pushd redis
    - make
    - popd
    # Run uwhoisd
    - pushd uwhoisd
    - python setup.py install
    - ../redis/src/redis-server extra/redis.conf --daemonize yes
    - sleep 10
    - uwhoisd extra/uwhoisd.ini &
    - popd
    # Other Python deps
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install codecov

before_script:
    - cp config.ini.sample config.ini
    - redis/src/redis-server --port 6334  --daemonize yes
    - sleep 10

script:
    - ./worker.py &
    - ./runapp.py &
    - sleep 5
    - curl http://0.0.0.0:5100/
    - sleep 20

after_success:
    - coveralls
    - codecov

