language: python

python:
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"

sudo: required
dist: xenial

install:
    - pip install pipenv
    - pushd ..
    # Faup
    - git clone https://github.com/stricaud/faup.git
    - pushd faup/build
    - cmake .. && make
    - sudo make install
    - sudo ldconfig
    - popd
    # redis
    - git clone https://github.com/antirez/redis.git
    - pushd redis
    - git checkout 5.0
    - make
    - popd
    # Run uwhoisd
    - git clone https://github.com/Rafiot/uwhoisd.git
    - pushd uwhoisd
    - pipenv install
    - echo UWHOISD_HOME="'`pwd`'" > .env
    - pipenv run start.py
    - popd
    # Get back in the project directory
    - popd
    # Other Python deps
    - pipenv install
    - echo URLABUSE_HOME="'`pwd`'" > .env

before_script:
    - cp website/config/config.ini.sample website/config/config.ini

script:
    - pipenv run start.py
    - sleep 2
    - pipenv run start_website.py &
    - sleep 5
    - curl http://0.0.0.0:5200/
    - pushd client
    - python tests/tests.py
    - popd
